// message
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
// modal
export const CHANGE_LANGUAGE_MODAL_STATUS = 'CHANGE_LANGUAGE_MODAL_STATUS';
export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
// side menu
export const CHANGE_SIDE_MENU_STATUS = 'CHANGE_SIDE_MENU_STATUS';
export const CHANGE_ACTIVE_MENU = 'CHANGE_ACTIVE_MENU';
// parameters
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_STARS = 'CHANGE_STARS';
export const CHANGE_TIME = 'CHANGE_TIME';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_TAGGED = 'CHANGE_TAGGED';
export const CHANGE_TAB = 'CHANGE_TAB';
// searchResult
export const CHANGE_LOADING_PAGE_STATUS = 'CHANGE_LOADING_PAGE_STATUS';
export const CHANGE_TOTAL_COUNT = 'CHANGE_TOTAL_COUNT';
export const RESET_ITEMS = 'RESET_ITEMS';
export const APPEND_ITEMS = 'APPEND_ITEMS';
// setting
export const ADD_SITE = 'ADD_SITE';
export const DELETE_SITE = 'DELETE_SITE';
// detail
export const SET_CNODEJS_TOPIC = 'SET_CNODEJS_TOPIC';
export const SET_SEGMENTFAULT_ARTICLE = 'SET_SEGMENTFAULT_ARTICLE';
export const SET_SEGMENTFAULT_QUESTION = 'SET_SEGMENTFAULT_QUESTION';
export const SET_SEGMENTFAULT_ANSWERS = 'SET_SEGMENTFAULT_ANSWERS';
